import type { Metadata } from "next";
import "./globals.css";
import {Montserrat , Fraunces} from "next/font/google"
const montserrat = Montserrat({
  subsets:["latin"],
  weight: ["500","700"],
  variable:"--font-montserrat",
});
const fraunces = Fraunces({
  subsets:["latin"],
  weight: ["700"],
  variable:"--font-fraunces",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${fraunces.variable}`}>
      <body className="flex flex-col items-center justify-center bg-[hsl(30,38%,92%)] p-3 min-h-[100%] h-[100%] sm:h-screen "
      >
        {children}
      </body>
    </html>
  );
}
